apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  config.yaml: |
    server:
        applicationConnectors:
          - type: http
            port: 8080
        adminConnectors:
          - type: http
            port: 8081
    database:
      # the name of your JDBC driver
      driverClass: com.mysql.cj.jdbc.Driver
    
      # the username
      user: root
    
      # the password
      password: admin
    
      # the JDBC URL
      url: jdbc:mysql://127.0.0.1:3306/oracle?allowPublicKeyRetrieval=true&useSSL=false
    
      # any properties specific to your JDBC driver:
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate.show_sql: true
        hibernate.jdbc.batch_size: 20
    
      # the maximum amount of time to wait on an empty pool before throwing an exception
      maxWaitForConnection: 1s
    
      # the SQL query to run when validating a connection's liveness
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
    
      # the minimum number of connections to keep open
      minSize: 8
    
      # the maximum number of connections to keep open
      maxSize: 32
    
      # whether or not idle connections should be validated
      checkConnectionWhileIdle: false
  
    logging:
    
      # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
      level: INFO
    
      # Logger-specific levels.
      loggers:
    
        # Sets the level for 'com.example.app' to DEBUG.
        com.oracle.mytest: INFO
    
        # Redirects SQL logs to a separate file
        org.hibernate.SQL:
          level: INFO

    # Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
    # Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
    # Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz
    appenders:
      - type: console
      - type: file
        threshold: INFO
        logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
        currentLogFilename: /tmp/application.log
        archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
        archivedFileCount: 7
        timeZone: UTC
        maxFileSize: 10MiB
 