#FROM openjdk:8-jre-alpine

#LABEL maintainer "YOUR NAME youremail@example.com"

#COPY target/mytest-0.0.1-SNAPSHOT.jar application.jar

#EXPOSE 8080 8081
#ENTRYPOINT ["java", "-jar", "/application.jar", "server", "/home/config/config.yaml"]
#FROM openjdk:8-jre-alpine

#ADD target/mytest-0.0.1-SNAPSHOT.jar /data/mytest-0.0.1-SNAPSHOT.jar

#ADD example.keystore /data/example.keystore

#ADD task.yml /data/task.yml

#RUN java -jar target/mytest-0.0.1-SNAPSHOT.jar db migrate /data/task.yml

#CMD java -jar target/mytest-0.0.1-SNAPSHOT.jar server /data/mytest-0.0.1-SNAPSHOT.yml

#EXPOSE 8080
FROM adoptopenjdk/openjdk16
COPY task.yml /data/oracle/task.yml
COPY example.keystore /data/oracle/example.keystore
COPY /target/mytest-0.0.1-SNAPSHOT.jar /data/oracle/mytest-0.0.1-SNAPSHOT.jar

WORKDIR /data/oracle

RUN java -version

CMD ["java","-jar","mytest-0.0.1-SNAPSHOT.jar","server","task.yml"]

EXPOSE 8080-8081